### ISSUE TITLE
I can't get this to work - kex_exchange_identification: Connection closed by remote host

### ISSUE THREAD

**Issue by mcwnuq** [charmbracelet/wishlist#9]
Hi,
When i try to connect
`ssh -o 'ForwardAgent=yes' -o 'UserKnownHostsFile=/dev/null' -p 2222 localhost`
I got an error
 `kex_exchange_identification: Connection closed by remote host`
 Config
```
mcwnuq@xxxxxx > ~/wishlist > cat .wishlist/config.yaml
listen: 127.0.0.1
port: 2222

endpoints:
- name: xxx.xx
  address: xxx.xx:xxxx
  user: xxx

users:
- name: mcwnuq
  public-keys:
  - id_rsa
```
Docker command
`docker run -p 2222:2222 -v $PWD/.wishlist:/.wishlist docker.io/charmcli/wishlist:latest`

PS:
ssh-add -l
`2048 SHA256:XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX+XXXXX /home/mcwnuq/.ssh/id_rsa (RSA)`

**Comment by caarlos0** [comment]
You need to listen on `0.0.0.0`, otherwise it's not exposed outside the container. `0.0.0.0` is the default, so you can also just remove that line. 🙏

**Comment by mcwnuq** [comment]
OK, thank you very much! I appreciate it! ;) 
But now i had other problem. :( 
Now when I try to connect i got this
`mcwnuq@localhost: Permission denied (publickey).`
And in the wishlist logs there is
`2022/01/12 11:47:40 invalid key for user "mcwnuq": ssh: no key found`
Where should i put my local machine public key? In the `.wishlist`?
Is this due to ssh key forwarding not working?

**Comment by caarlos0** [comment]
can you confirm that the public key in the config is the correct one?

```yaml
users:
- name: mcwnuq
  public-keys:
  - id_rsa # <----- here
```

that error seems to indicate your public key is not in the allow list

**Comment by mcwnuq** [comment]
It should be path / file name or key name?
```
ssh-add -k
Identity added: /home/mcwnuq/.ssh/id_rsa (/home/mcwnuq/.ssh/id_rsa)
ssh-add -l
2048 SHA256:XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX+XXXXX /home/mcwnuq/.ssh/id_rsa (RSA)
```
Where should i put my local machine public key? In the `.wishlist`?

**Comment by caarlos0** [comment]
you should put the pubkey in plain text there:

```yaml
users:
- name: mcwnuq
  public-keys:
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDXTlLdHrS+PRjQ6gfWXBy17...etc foo@bar
```
